--- 
- 
  become: true
  hosts: dev
  tasks: 
    - 
      command: "{{ item }}"
      name: "install docker"
      with_items: 
         - apt update
         - apt-get install -y ca-certificates curl gnupg lsb-release
         - mkdir -p /etc/apt/keyrings
         - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
         - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
         - apt-get update -y 
         - apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y 
    - 
      docker_container: 
        image: "sahilthakre123/sampleapp:{{DOCKER_TAG}}"
        name: sampleapp
        published_ports: 
          - "0.0.0.0:8553:8080"
        state: started
